### ISSUE TITLE
This Website is too beautiful

### ISSUE THREAD

**Issue by ghost** [Amorpheuz/amorpheuz.github.io#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
Hi Yash! The issue I have with this website is that it is too beautiful. Hahaha. This is really great. I love the dark and light theme. When I am ready to revamp my portfolio, I could use some ideas. I also love the way you made a heading for the sections as fetchProjects() and fetchBlogPosts(). It's so unique. That's what this issue is for. Feel free to close it anytime

**Additional context**

**Comment by Amorpheuz** [comment]
Thanks Karen ♥ Feel free to draw inspirations as you like!
